### ISSUE TITLE
Add processing of YAML-format configuration file

### ISSUE THREAD

**Issue by codders** [advancedtelematic/sota_client_cpp#2]

**Comment by embmk** [comment]
It seems I made a mistake when creating the branch for the logging framework by naming the branch feat/2/.. but this was more like a feature number, not an issue number, now i wonder

**Comment by embmk** [comment]
I have problems using my login at Garage. It tells me to verify my email address. But after clicking the verification link Garage tells me that the account is now activated. But when logging in afterwards garage tells me to use my verification link again...
As I managed reading from yml files I'll continue using dummy data.

**Comment by codders** [comment]
I'll check to make sure your account is enabled...

**Comment by codders** [comment]
Should be fixed for you now.

**Comment by embmk** [comment]
I'll add a commandline option for the config file using "-c" and add the example config.
One thing came to my mind right now when thinking about breaking the build - should I change the travis config by extending it with the yaml library, it doesn't look that complicated...

**Comment by embmk** [comment]
I changed the travis configuration by adding the libyaml-cpp-dev library, but maybe this library has to be installed manually. I'm now waiting for clarification concerning the location of an example config.

**Comment by codders** [comment]
That should be all that's required. The package has to be in Ubuntu Trusty, but aside from that all you have to do is add the line and CI will find it.

**Comment by embmk** [comment]
I added an example configuration. The build still fails due to a missing header yaml-cpp/yaml.h. I double checked that the trusty package does the same as the xenial package I'm using and when looking into the deb archive it contains the yaml.h and should put it at the same place. Maybe someone should check if the package is installed on the server.

> http://packages.ubuntu.com/trusty/libyaml-cpp-dev

> usr/include/yaml-cpp/

**Comment by codders** [comment]
You spelled the library slightly wrong in the travis config - libbyaml-cpp-dev vs. libyaml-cpp-dev. I've fixed it.

**Comment by codders** [comment]
Buh. Okay. So the Travis environment is a bit of a pain. I've switched to building inside Docker for CI purposes. Now we just add new libraries to the Docker container, and we don't have to worry about what Travis has whitelisted.

**Comment by codders** [comment]
Are you okay to proceed with this ticket now? Will you write some tests and make a pull request for it? Once this is merged, you will need to rebase any other branches against master so that you get the build system changes.

**Comment by embmk** [comment]
I can quickly add some testcases as I did for commandline options. I would like to implement some simple testcases with actual code but therefore I have to study cmakes test functionality a bit.
